name: Auto Poster System v5.2 - Dubai Time

on:
  schedule:
    # --- جميع الأوقات بتوقيت دبي (UTC+4) ---
    # تم تعديل الأوقات لتكون بتوقيت دبي (اطرح 4 ساعات من توقيت غرينتش)
    # Periodo mattutino (inizia alle 09:30 Dubai)
    - cron: '30 5 * * *'   # 09:30 Dubai = 05:30 UTC
    - cron: '0 6 * * *'    # 10:00 Dubai = 06:00 UTC
    - cron: '45 6 * * *'   # 10:45 Dubai = 06:45 UTC
    # Periodo pomeridiano (inizia alle 13:30 Dubai)
    - cron: '30 9 * * *'   # 13:30 Dubai = 09:30 UTC
    - cron: '0 10 * * *'   # 14:00 Dubai = 10:00 UTC
    - cron: '45 10 * * *'  # 14:45 Dubai = 10:45 UTC
    # Periodo serale (inizia alle 18:30 Dubai)
    - cron: '30 14 * * *'  # 18:30 Dubai = 14:30 UTC
    - cron: '0 15 * * *'   # 19:00 Dubai = 15:00 UTC
    - cron: '45 15 * * *'  # 19:45 Dubai = 15:45 UTC
    # Periodo notturno (inizia alle 22:30 Dubai)
    - cron: '30 18 * * *'  # 22:30 Dubai = 18:30 UTC
    - cron: '0 19 * * *'   # 23:00 Dubai = 19:00 UTC
    - cron: '45 19 * * *'  # 23:45 Dubai = 19:45 UTC
  workflow_dispatch: {}     # للسماح بالتشغيل اليدوي

jobs:
  # ===================================================================
  # JOB 1: تثبيت الاعتماديات وحفظها في التخزين المؤقت
  # ===================================================================
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Installing dependencies..."
          npm install --omit=dev --prefer-offline --no-audit --no-fund

  # ===================================================================
  # JOB 2: إعداد تناوب الحسابات اليومي (يعمل مرة واحدة فقط)
  # ===================================================================
  setup_daily_rotation:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: github.event.schedule == '30 5 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
      - name: Run Daily Zapier Rotation Setup
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          ZAPIER_WEBHOOKS: ${{ secrets.ZAPIER_WEBHOOKS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node src/setup_rotation.js
        timeout-minutes: 5

  # ===================================================================
  # JOB 3: تشغيل نظام النشر (يعمل 12 مرة في اليوم)
  # ===================================================================
  process-post:
    runs-on: ubuntu-latest
    needs: [install-dependencies, setup_daily_rotation]
    if: always() 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Auto Poster
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          ZAPIER_WEBHOOKS: ${{ secrets.ZAPIER_WEBHOOKS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "🚀 Starting Auto Poster System..."
          node src/auto_poster.js
        timeout-minutes: 10
